#!/usr/bin/env perl

use v5.36;

use FindBin;
use local::lib "$FindBin::Bin/../local";

use utf8;
use open ':std', ':encoding(UTF-8)';

use JSON;

(scalar @ARGV) > 0 or die "No rule file\n";

my $rule_file = $ARGV[0];
(-e $rule_file) or die "Rule file not exist: ${rule_file}\n";

open my $FH, "<:encoding(utf-8)", $rule_file or die "Unable to open rule file: ${rule_file}\n";

# Slurp the file.
my $json_text = do { local $/; <$FH> };

close $FH;

my @rules = @{JSON->new->canonical(0)->decode($json_text)};

say (scalar @rules);