#!/usr/bin/env perl

use v5.36;
use builtin qw(true false);

use FindBin;
use local::lib "$FindBin::Bin/../../local";

use utf8;
use open ':std', ':encoding(UTF-8)';

use JSON;
use Tie::IxHash;

(scalar @ARGV) > 0 or die "No JSON file\n";

my $json_file = $ARGV[0];
(-e $json_file) or die "JSON file not exist: ${json_file}\n";

open my $FH, "<:encoding(utf-8)", $json_file or die "Unable to open rule file: ${json_file}\n";

# Slurp the file.
my $json_text = do { local $/; <$FH> };

close $FH;

my @rules = @{JSON->new->canonical(0)->decode($json_text)};

my @hanparse_rules = ();
for my $rule (@rules) {
    tie my %rule_data, 'Tie::IxHash';

    $rule_data{'pattern'} = join '', (grep { !ref($_) } @{$rule->{'pattern'}});

    my $base = $rule->{'metadata'}->{'base'};
    $rule_data{'base'} = $base if ($base);

    $rule_data{'type'} = $rule->{'metadata'}->{'type'};
    $rule_data{'meaning'} = $rule->{'metadata'}->{'meaning'};

    my @categories;
    for my $elem (@{ $rule->{'pattern'}[0] }) {
        if (ref $elem eq 'HASH' && exists $elem->{'category'}) {
            push @categories, $elem->{'category'};
        }
    }

    $rule_data{'after'} = join '/', @categories;

    my $requiresBatchim = $rule->{'metadata'}->{'requiresBatchim'};
    $rule_data{'requiresBatchim'} = ($requiresBatchim eq "true" ? true : false) if ($requiresBatchim);

    $rule_data{'note'} = $rule->{'metadata'}->{'note'};

    my $fusionJamo = $rule->{'metadata'}->{'fusionJamo'};
    $rule_data{'fusionJamo'} = $fusionJamo if ($fusionJamo);
    
    push @hanparse_rules, \%rule_data;
}

say JSON->new->canonical(0)->encode(\@hanparse_rules);
